from .users_serializers import UserSerializer
from .students_serializers import StudentSerializer
from .teachers_serializers import TeacherSerializer
from .admins_serializers import AdminSerializer
from .courses_serializers import CourseSerializer, BrowseCourseSerializer
from .course_objects_serializers import LessonSerializer, AssignmentSerializer
from .enrollments_serializers import EnrollmentSerializer