# Generated by Django 5.1.5 on 2025-02-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_no',
        ),
    ]
